### ISSUE TITLE
error with Python 3.10.0

### ISSUE THREAD

**Issue by sky59** [panzi/verify-ehc#35]
here is the error description: (should the py file be changed or Python problem?)

Traceback (most recent call last):
  File "/ehc/verify_ehc.py", line 2493, in <module>
    main()
  File "/ehc/verify_ehc.py", line 2400, in main
    certs = download_ehc_certs(parse_sources(args.certs_from), check_kid, certs_table)
  File "/ehc/verify_ehc.py", line 1400, in download_ehc_certs
    certs.update(downloader(check_kid))
  File "/ehc/verify_ehc.py", line 747, in download_de_certs
    pubkey = get_root_cert('DE').public_key() # type: ignore
  File "/ehc/verify_ehc.py", line 1525, in get_root_cert
    return ROOT_CERT_DOWNLOADERS[source]()
  File "/ehc/verify_ehc.py", line 1483, in get_de_root_cert
    return HackCertificate(get_de_root_pubkey())
TypeError: Can't instantiate abstract class HackCertificate with abstract method tbs_precertificate_bytes

**Comment by panzi** [comment]
I'm still on Python 3.9 and an old cryptography version, but did commit 5c00825de3df68d40e26368908cdacf008a75b84 fix it for you?

**Comment by sky59** [comment]
Yes, I added 4 lines and it works now! Thanx

**Comment by panzi** [comment]
Great!
